package com.xworkz.collectionLombok.constants;

public enum Address {

	GOPALAPURA_BINNIPETE, MALLESHWARAM, BELLANDUR, ASHOK_NAGAR, RAJAJINAGAR, WHITEFIELD, KANNAMANGALA, MG_ROAD,
	MAHADEVAPURA, KORAMANGALA;

}
